@baseUrl = http://localhost:3000

# Colección de pruebas para VS Code REST Client
# Abre este archivo y usa "Send Request" arriba de cada bloque.

### Ping root (diagnóstico)
GET {{baseUrl}}/
Accept: application/json

### Statements - Misión
GET {{baseUrl}}/api/statements/mission
Accept: application/json


### Statements - Visión
GET {{baseUrl}}/api/statements/vision
Accept: application/json


### Form stats
GET {{baseUrl}}/api/form-stats
Accept: application/json


### News
GET {{baseUrl}}/api/news
Accept: application/json


### Prueba adicional: ruta no encontrada (ejemplo)
GET {{baseUrl}}/api/services/nonexistent-id
Accept: application/json

